version: '3.9'

services:
  caramelo-db:
    container_name: caramelo-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: caramelo-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/pg:/data/postgres

  caramelo-api:
    container_name: caramelo-api
    build:
      context: ./caramelo2-api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@caramelo-db:5432/caramelo-db
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://caramelo-web:3000
      - DEBUG=True
      - SECRET_KEY=test
    volumes:
      - ./caramelo2-api:/app
    depends_on:
      - caramelo-db

  caramelo-web:
    container_name: caramelo-web
    build:
      context: ./caramelo2-public
      dockerfile: Dockerfile
    environment:
      - API_URL=http://caramelo-api:8000
      - NEXTAUTH_SECRET=9831762987369182
      - NEXTAUTH_URL=http://demo.caramelopos.com
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - caramelo-api
